/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sse Events
         * @description Server-Sent Events stream.
         *         - Sends JSON events as `data: {...}
         *
         *     `
         *         - Emits a keepalive comment every 15s so proxies don't time out.
         *         - Events are delivered via Redis pub/sub so ARQ workers can broadcast
         *           to all connected FastAPI processes.
         */
        get: operations["sse_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Ingest file upload. User context from trusted Next.js gateway headers.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_invoices_get"];
        put?: never;
        /** Create Invoices */
        post: operations["create_invoices_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invoice */
        get: operations["get_invoice_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Invoice */
        patch: operations["patch_invoice_invoices__invoice_id__patch"];
        trace?: never;
    };
    "/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vendors */
        get: operations["list_vendors_vendors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{vendor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor By Id */
        get: operations["get_vendor_by_id_vendors__vendor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Structured
         * @description Enqueue an async structured-extraction job (CSV or JSON) for a document
         *     that has already been uploaded via POST /ingest.
         *
         *     Returns a job_id immediately. Poll GET /jobs/{job_id} for status and result.
         */
        post: operations["extract_structured_extract_structured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract/unstructured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Unstructured
         * @description Enqueue an async unstructured-extraction job (PDF → LLM pipeline) for a
         *     document that has already been uploaded via POST /ingest.
         *
         *     Returns a job_id immediately. Poll GET /jobs/{job_id} for status and result.
         */
        post: operations["extract_unstructured_extract_unstructured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List alerts for the current org with optional filtering.
         *
         *     Org context derived from authenticated user's JWT.
         */
        get: operations["list_alerts_alerts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Alert
         * @description Update an alert's status / acknowledgement fields.
         *
         *     This is used by the UI to acknowledge or dismiss alerts. The org scope is
         *     enforced by always including the current org_id in the update query.
         */
        patch: operations["patch_alert_alerts__alert_id__patch"];
        trace?: never;
    };
    "/alerts/{alert_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Alert Endpoint
         * @description Generate (or return cached) an evidence-backed explanation for an alert.
         *
         *     Supported alert types: unit_price_delta, vendor_volume_spike, duplicate_invoice.
         *     Pass ?force=true to regenerate an existing explanation.
         */
        post: operations["explain_alert_endpoint_alerts__alert_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Poll the status of an ARQ background job.
         *
         *     Returns one of: queued | in_progress | complete | not_found | failed
         *
         *     When status == "complete" and the job succeeded, the result payload
         *     (invoice_id, warnings, etc.) is included under the "result" key.
         *     When status == "complete" but the job raised an exception, the error
         *     message is included under the "error" key.
         */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertUpdatePayload
         * @description Payload for acknowledging or dismissing an alert.
         *
         *     For v1 we keep this intentionally simple:
         *       - callers must always supply a new `status` value (e.g. "open",
         *         "acknowledged", "dismissed").
         *       - the backend derives `acknowledged_at` automatically whenever an
         *         alert moves out of the "open" state.
         */
        AlertUpdatePayload: {
            /** Status */
            status: string;
            /** Acknowledged By */
            acknowledged_by?: string | null;
        };
        /** Body_ingest_ingest_post */
        Body_ingest_ingest_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Invoice */
        "Invoice-Input": {
            /** Vendor */
            vendor: string;
            /** Invoice No */
            invoice_no: string;
            /**
             * Invoice Date
             * Format: date
             */
            invoice_date: string;
            /** Currency */
            currency: string;
            /** Subtotal */
            subtotal: number | string;
            /** Tax */
            tax: number | string;
            /** Total */
            total: number | string;
            /** Due Date */
            due_date?: string | null;
            /** Lines */
            lines: components["schemas"]["InvoiceLine-Input"][];
        };
        /** Invoice */
        "Invoice-Output": {
            /** Vendor */
            vendor: string;
            /** Invoice No */
            invoice_no: string;
            /**
             * Invoice Date
             * Format: date
             */
            invoice_date: string;
            /** Currency */
            currency: string;
            /** Subtotal */
            subtotal: string;
            /** Tax */
            tax: string;
            /** Total */
            total: string;
            /** Due Date */
            due_date?: string | null;
            /** Lines */
            lines: components["schemas"]["InvoiceLine-Output"][];
        };
        /** InvoiceLine */
        "InvoiceLine-Input": {
            /** Sku */
            sku?: string | null;
            /** Desc */
            desc: string;
            /** Qty */
            qty: number | string;
            /** Unit Price */
            unit_price: number | string;
            /** Line Total */
            line_total: number | string;
        };
        /** InvoiceLine */
        "InvoiceLine-Output": {
            /** Sku */
            sku?: string | null;
            /** Desc */
            desc: string;
            /** Qty */
            qty: string;
            /** Unit Price */
            unit_price: string;
            /** Line Total */
            line_total: string;
        };
        /** InvoicePatch */
        InvoicePatch: {
            /** Vendor Id */
            vendor_id?: string | null;
            /** Invoice No */
            invoice_no?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Currency */
            currency?: string | null;
            /** Subtotal */
            subtotal?: number | null;
            /** Tax */
            tax?: number | null;
            /** Total */
            total?: number | null;
            /** Lines */
            lines?: components["schemas"]["InvoiceLine-Input"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vendor */
        Vendor: {
            /**
             * Id
             * Format: uuid
             * @description Vendor UUID
             * @example 98681ed3-d1e5-4440-b249-85f181f32b0e
             */
            id: string;
            /**
             * Name
             * @description Display name of the vendor
             * @example Apex Office Supply
             */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sse_events_events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_invoices_invoices_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoices_invoices_post: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_invoice_invoices__invoice_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vendors_vendors_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vendor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_by_id_vendors__vendor_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vendor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_structured_extract_structured_post: {
        parameters: {
            query?: {
                raw_doc_id?: number | null;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_unstructured_extract_unstructured_post: {
        parameters: {
            query?: {
                raw_doc_id?: number | null;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_alerts__get: {
        parameters: {
            query?: {
                /** @description Filter by alert status */
                status?: string | null;
                /** @description Filter by severity */
                severity?: string | null;
                /** @description Max number of alerts */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_alert_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_alert_endpoint_alerts__alert_id__explain_post: {
        parameters: {
            query?: {
                /** @description Regenerate even if a cached explanation exists */
                force?: boolean;
            };
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-business-user-id"?: string | null;
                "x-org-id"?: string | null;
                "x-user-role"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
